language: rust
rust:
  - nightly
os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  global:
    - CC="gcc-4.8" CPP="gcc-4.8 -E" CXX="g++-4.8"
  matrix:
    - FEATURES=""
    - FEATURES="--features debugmozjs"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache; fi

script:
  - ccache -z
  - CCACHE=$(which ccache) travis_wait cargo build --verbose $FEATURES
  - CCACHE=$(which ccache) cargo test --verbose $FEATURES
  - ccache -s

notifications:
  webhooks: http://build.servo.org:54856/travis

cache: ccache
